labels:
- emoji: "🔨"
  title: ".*build(:|\\().*"
- emoji: "🏗️"
  title: ".*chore(:|\\().*"
- emoji: "🤖"
  title: ".*ci(:|\\().*"
- emoji: "📚"
  title: ".*docs(:|\\().*"
- emoji: "✨"
  title: ".*feat(:|\\().*"
- emoji: "🐛"
  title: ".*fix(:|\\().*"
- emoji: "🚑"
  title: ".*hotfix(:|\\().*"
- emoji: "♻️"
  title: ".*refactor(:|\\().*"
- emoji: "↩️"
  title: ".*revert(:|\\().*"
- emoji: "🎨"
  title: ".*style(:|\\().*"
- emoji: "📱"
  title: ".*responsive(:|\\().*"
- emoji: "♿️"
  title: ".*a11y(:|\\().*"
- emoji: "🧪"
  title: ".*test(:|\\().*"

