name: 'Prefix Emoji to PR Title'
description: 'Prefix your PR title with the correct emoji'
author: '@lisi_linhart'

# Define your inputs here.
inputs: 
  config_path:
    description: 'Path for emoji labeling'
    default: '.github/emoji-labels.yml'
  token:
    description: 'GitHub Token'
    required: true

runs:
  using: node20
  main: dist/index.js

branding:
  icon: "git-pull-request"
  color: "yellow"