name: 'Emojify PR Title'
description: 'Prefix your PT title with the correct emoji'
author: '@lisi_linhart'

# Define your inputs here.
inputs: 
  config_path:
    description: 'Path for emoji labeling'
    default: '.github/emoji-labels.yml'
  token:
    description: 'GitHub Token'
    required: true

runs:
  using: node20
  main: dist/index.js
